import pandas as pd

questions_data = [
    {
        "Question": "It is likelihood that a threat will actually materialize and cause harm to a system or network:",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "Vulnerability",
        "Choice2": "Risk",
        "Choice3": "Malware",
        "Choice4": "CIA",
    },
    {
        "Question": "Type of cybersecurity attack that targets a network, website, or application with the intention of making it unavailable to legitimate user:",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "Phishing",
        "Choice2": "Man-in-the-middle (MITM)",
        "Choice3": "Denial of Service (DoS)",
        "Choice4": "SQL injection",
    },
    {
        "Question": "It is type of algorithm which takes any size of data and converts it to a fixed length of data:",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "Hashing",
        "Choice2": "Encryption",
        "Choice3": "Decryption",
        "Choice4": "Assymetric encryption",
    },
    {
        "Question": "To send encrypted message between Alice and Bob (where Alice is sender and Bob is receiver) what are the minimum and sufficient keys required:",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "Alice’s public key and Bob’s private key",
        "Choice2": "Alice’s private key and Bob’s public key",
        "Choice3": "Bob’s public key and Bob’s private key",
        "Choice4": "Both a and b",
    },
    {
        "Question": "Which linux command is an example of generating a 256 bit key",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "openssl rand 256 -out keyfile",
        "Choice2": "openssl enc -aes-256-cbc -pass pass:test -p -in image.png -out file.enc",
        "Choice3": "openssl enc -aes-256-cbc -k secret -P -md sha1",
        "Choice4": "openssl enc -aes-256-cbc -pass pass:test -d -in file.enc -out key.png -P",
    },
    {
        "Question": "which command is used to get salt,key and iv values:",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "-p",
        "Choice2": "-d",
        "Choice3": "-D",
        "Choice4": "-P",
    },
    {
        "Question": "Which of the following is incorrect about SSL/TLS handshake process:",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "First TCP handshake is done between client and server, then SSL handshake starts",
        "Choice2": "First SSL handshake is completed then TCP handshake between client and server begins.",
        "Choice3": "Both the TCP and SSL handshakes occur simultaneously.",
        "Choice4": "The TCP handshake is never performed at any point during the process.",
    },
    {
        "Question": "Below is the example of Cipher Suite\nTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P521\nWhich part of the cipher suite denotes the Signature",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "ECDHE",
        "Choice2": "ECDSA",
        "Choice3": "SHA384",
        "Choice4": "P384",
    },
    {
        "Question": "Below is the example of Cipher Suite\nTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P521\nWhich part of the cipher suite denotes the Authentication",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "ECDHE",
        "Choice2": "ECDSA",
        "Choice3": "SHA384",
        "Choice4": "P384",
    },
    {
        "Question": "In ___ , the owner of a resources has control over granting or revoking access permission.",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "MAC",
        "Choice2": "DAC",
        "Choice3": "RBAC",
        "Choice4": "ABAC",
    },
    {
        "Question": "Which of the following is NOT  a form of malware:",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "Rootkit",
        "Choice2": "Worm",
        "Choice3": "Trojan horse",
        "Choice4": "BotNetSafe",
    },
    {
        "Question": "It is a type of cryptography where block cipher algorithms are applied three times to each data block",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "AES",
        "Choice2": "DES",
        "Choice3": "Triple AES",
        "Choice4": "Triple DES",
    },
    {
        "Question": "It enables public key encryption and is widely used to secure sensitive data, particularly when it is being sent over insecure network:",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "Rivest Shamir Adleman (RSA)",
        "Choice2": "Digital Signature Standard (DSS)",
        "Choice3": "Diffie-Hellman exchange method",
        "Choice4": "Elliptical Curve Cryptography (ECC)",
    },
     {
        "Question": "It is a method of hiding information within another file or images:",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "Data Encryption",
        "Choice2": "Digital Forensics",
        "Choice3": "Steganography",
        "Choice4": "Cryptology",
    },
    {
        "Question": "What is the primary vulnerability exploited in an SQL Injection attack?",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "Buffer Overflow",
        "Choice2": "Insufficient Input Validation",
        "Choice3": "Cross-Site Scripting (XSS)",
        "Choice4": "XML External Entity Injection (XXE)",
    },
    {
        "Question": "This command calculates the MD5 checksum of a string by piping it through md5sum",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": 'md5sum -c “your_string”',
        "Choice2": 'echo -n “your_string” | xargs -0 md5sum',
        "Choice3": 'echo -n “your_string” | md5sum -b filename',
        "Choice4": 'echo -n “your_string” | md5sum',
    },
    {
        "Question": "Which of the following hashing algorithm is considered weak:",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "SHA-256",
        "Choice2": "SHA-512",
        "Choice3": "MD5",
        "Choice4": "Blake2",
    },
    {
        "Question": "“Birthday Attack” is attack on which property:",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "Confidentiality",
        "Choice2": "Integrity",
        "Choice3": "Collison resistance of hash functions",
        "Choice4": "Key exchange security",
    },
    {
        "Question": "What filter can you use in Wireshark to identify HTTP traffic containing a flag?",
        "Type": "MCQ",
        "Answer": "c",
        "Choice1": "Tcp.flags==0x02",
        "Choice2": "http.request.method==GET",
        "Choice3": 'frame contains “FLAG”',
        "Choice4": 'dns.qry.name contains “ctf.com”',
    },
    {
        "Question": "Which tool should you use first to locate a hidden image file?",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "strings",
        "Choice2": "steghide",
        "Choice3": "exiftool",
        "Choice4": "All of the above",
    },
    {
        "Question": "A suspicious program on a laptop shows: Mov eax, 0x466c6167. What does eax hold?",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "FLAG",
        "Choice2": "CTF",
        "Choice3": "HACK",
        "Choice4": "SECRET",
    },
    {
        "Question": "Which tool might help you uncover hidden data in an audio file?",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "Sonic Visualizer",
        "Choice2": "Binwalk",
        "Choice3": "ffmpeg",
        "Choice4": "stegsolve",
    },
    {
        "Question": "What should you try instead if SQL injection with '--' fails?",
        "Type": "MCQ",
        "Answer": "a",
        "Choice1": "admin’ #",
        "Choice2": "admin’ OR 1=1 –",
        "Choice3": "admin’ /*",
        "Choice4": "admin’ AND ‘1’=’1’",
    },
    {
        "Question": "Which hashing algorithm produced this hash: 5d41402abc4b2a76b9719d911017c592?",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "SHA-256",
        "Choice2": "MD5",
        "Choice3": "SHA-1",
        "Choice4": "Bcrypt",
    },
    {
        "Question": "Where should Shivam look for the hidden flag on the website?",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "Try different directories like /admin or /hidden",
        "Choice2": "Check robots.txt for disallowed paths",
        "Choice3": "Inspect JavaScript files for sensitive data",
        "Choice4": "All of the above",
    },
    {
        "Question": "What command should Shivam use for SQL Injection?",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "' OR 1=1",
        "Choice2": "' OR 1=1 --",
        "Choice3": "' OR 1=1 /*",
        "Choice4": "' AND 1=2 --",
    },
    {
        "Question": "Where might the flag be stored after a successful SQL injection?",
        "Type": "MCQ",
        "Answer": "d",
        "Choice1": "users table",
        "Choice2": "flag or ctf_flags table",
        "Choice3": "/var/www/html/config.php",
        "Choice4": "All of the above",
    },
    {
        "Question": "Decrypt ROT13: Gur synt vf: SYNT{jbj_lbh_ner_travhf}",
        "Type": "MCQ",
        "Answer": "b",
        "Choice1": "FLAG{uwu_yoo_are_tensai}",
        "Choice2": "FLAG{wow_you_are_genius}",
        "Choice3": "CTFS{yay_she_was_mikasa}",
        "Choice4": "CTFS{pfp_int_for_greats}",
    },
]

# Add missing columns with empty values or defaults
for q in questions_data:
    for col in ["Choice5", "Choice6", "Marks", "Negative Marks", "Answer Keywords", "Answer Keywords marks", "Image", "Duration In Seconds", "Tag"]:
        q[col] = ""

# Create DataFrame
df = pd.DataFrame(questions_data)
# Set default marks: 1 for correct answers, 0 for negative marks
df["Marks"] = 1
df["Negative Marks"] = 0

# Save to CSV
csv_path = "formatted_questions.csv"
df.to_csv(csv_path, index=False)

csv_path
